hard_words = '''
intervention
manufacturer
environmental
presentation
passionfruit
revolutionary
introduction
consciousness
contemporary
intermediate
concentration
confrontation
intelligence
unimpossible
spokesperson
excommunication
consultation
announcement
intersection
responsibility
identification
contradiction
conglomerate
discriminate
characteristic
extraterrestrial
rehabilitation
discrimination
counterclockwise
demonstrator
compensation
qualification
supernatural
organisation
headquarters
prescription
neighborhood
demonstration
circumstance
constellation
administration
conservation
constituency
conversation
relationship
entertainment
superintendent
conservative
complication
understanding
civilization
continuation
supplementary
reproduction
jurisdiction
transmission
contribution
embarrassment
registration
investigation
disappointment
professional
preoccupation
comprehension
presidential
interference
recommendation
constitutional
representative
consideration
anticipation
interjection
comprehensive
accumulation
acquaintance
communication
satisfaction
constitution
correspondence
infrastructure
strikebreaker
inappropriate
refrigerator
architecture
disagreement
conventional
immunodeficiency'''.split()
